% Image category Classification

%place the database in same root folder where the code is placed
rootFolder = fullfile('database');

%create array of image sets

imgSets = [ imageSet(fullfile(rootFolder, 'accordion')), ...
            imageSet(fullfile(rootFolder, 'airplanes')), ...
            imageSet(fullfile(rootFolder, 'anchor')),...
            imageSet(fullfile(rootFolder, 'ant')),...
            imageSet(fullfile(rootFolder, 'barrel')),...
            imageSet(fullfile(rootFolder, 'bass')),...
            imageSet(fullfile(rootFolder, 'beaver')),...
            imageSet(fullfile(rootFolder, 'binocular')),...
            imageSet(fullfile(rootFolder, 'bonsai')),...
            imageSet(fullfile(rootFolder, 'brain')),...
            imageSet(fullfile(rootFolder, 'brontosaurus')),...
            imageSet(fullfile(rootFolder, 'buddha')),...
            imageSet(fullfile(rootFolder, 'butterfly')),...
            imageSet(fullfile(rootFolder, 'camera')),...
            imageSet(fullfile(rootFolder, 'canon')),...
            imageSet(fullfile(rootFolder, 'car')),...
            imageSet(fullfile(rootFolder, 'ceilingfan')),...
            imageSet(fullfile(rootFolder, 'cellphone')),...
            imageSet(fullfile(rootFolder, 'chair')),...
            imageSet(fullfile(rootFolder, 'chandelier')),...
            imageSet(fullfile(rootFolder, 'cougar_body')),...
            imageSet(fullfile(rootFolder, 'cougar_face')),...
            imageSet(fullfile(rootFolder, 'crab')),...
            imageSet(fullfile(rootFolder, 'crayfish')),...
            imageSet(fullfile(rootFolder, 'crocodile')),...
            imageSet(fullfile(rootFolder, 'crocodile_head')),...
            imageSet(fullfile(rootFolder, 'cup')),...
            imageSet(fullfile(rootFolder, 'dalmatian')),...
            imageSet(fullfile(rootFolder, 'dollar_bill')),...
            imageSet(fullfile(rootFolder, 'dolphin')),...
            imageSet(fullfile(rootFolder, 'dragonfly')),...
            imageSet(fullfile(rootFolder, 'electric_guitar')),...
            imageSet(fullfile(rootFolder, 'elephant')),...
            imageSet(fullfile(rootFolder, 'emu')),...
            imageSet(fullfile(rootFolder, 'euphonium')),...
            imageSet(fullfile(rootFolder, 'ewer')),...
            imageSet(fullfile(rootFolder, 'faces')),...
            imageSet(fullfile(rootFolder, 'ferry')),...
            imageSet(fullfile(rootFolder, 'flamingo')),...
            imageSet(fullfile(rootFolder, 'flamingo_head')),...
            imageSet(fullfile(rootFolder, 'garfield')),...
            imageSet(fullfile(rootFolder, 'gerenuk')),...
            imageSet(fullfile(rootFolder, 'gramophone')),...
            imageSet(fullfile(rootFolder, 'grand_piano')),...
            imageSet(fullfile(rootFolder, 'hawksbill')),...
            imageSet(fullfile(rootFolder, 'headphone')),...
            imageSet(fullfile(rootFolder, 'hedgehog')),...
            imageSet(fullfile(rootFolder, 'helicopter')),...
            imageSet(fullfile(rootFolder, 'ibis')),...
            imageSet(fullfile(rootFolder, 'inline_skate')),...
            imageSet(fullfile(rootFolder, 'joshua_tree')),...
            imageSet(fullfile(rootFolder, 'kangaroo')),...
            imageSet(fullfile(rootFolder, 'ketch')),...
            imageSet(fullfile(rootFolder, 'lamp')),...
            imageSet(fullfile(rootFolder, 'laptop')),...
            imageSet(fullfile(rootFolder, 'leopards')),...
            imageSet(fullfile(rootFolder, 'llama')),...
            imageSet(fullfile(rootFolder, 'lobster')),...
            imageSet(fullfile(rootFolder, 'lotus')),...
            imageSet(fullfile(rootFolder, 'mandolin')),...
            imageSet(fullfile(rootFolder, 'mayfly')),...
            imageSet(fullfile(rootFolder, 'menorah')),...
            imageSet(fullfile(rootFolder, 'metronome')),...
            imageSet(fullfile(rootFolder, 'minaret')),...
            imageSet(fullfile(rootFolder, 'motorbikes')),...
            imageSet(fullfile(rootFolder, 'nautilus')),...
            imageSet(fullfile(rootFolder, 'octopus')),...
            imageSet(fullfile(rootFolder, 'okapi')),...
            imageSet(fullfile(rootFolder, 'pagoda')),...
            imageSet(fullfile(rootFolder, 'panda')),...
            imageSet(fullfile(rootFolder, 'pigeon')),...
            imageSet(fullfile(rootFolder, 'pizza')),...
            imageSet(fullfile(rootFolder, 'platypus')),...
            imageSet(fullfile(rootFolder, 'pyramid')),...
            imageSet(fullfile(rootFolder, 'revolver')),...
            imageSet(fullfile(rootFolder, 'rhino')),...
            imageSet(fullfile(rootFolder, 'rooster')),...
            imageSet(fullfile(rootFolder, 'saxophone')),...
            imageSet(fullfile(rootFolder, 'schooner')),...
            imageSet(fullfile(rootFolder, 'scissors')),...
            imageSet(fullfile(rootFolder, 'scorpion')),...
            imageSet(fullfile(rootFolder, 'sea_horse')),...
            imageSet(fullfile(rootFolder, 'snoopy')),...
            imageSet(fullfile(rootFolder, 'soccer_ball')),...
            imageSet(fullfile(rootFolder, 'stapler')),...
            imageSet(fullfile(rootFolder, 'starfish')),...
            imageSet(fullfile(rootFolder, 'stegosaurus')),...
            imageSet(fullfile(rootFolder, 'stop_sign')),...
            imageSet(fullfile(rootFolder, 'strawberry')),...
            imageSet(fullfile(rootFolder, 'sunflower')),...
            imageSet(fullfile(rootFolder, 'tick')),...
            imageSet(fullfile(rootFolder, 'trilobite')),...
            imageSet(fullfile(rootFolder, 'umbrella')),...
            imageSet(fullfile(rootFolder, 'watch')),...
            imageSet(fullfile(rootFolder, 'water_lilly')),...
            imageSet(fullfile(rootFolder, 'wheelchair')),...
            imageSet(fullfile(rootFolder, 'wild_cat')),...
            imageSet(fullfile(rootFolder, 'windsor_chair')),...
            imageSet(fullfile(rootFolder, 'wrench')),...
            imageSet(fullfile(rootFolder, 'yin_yang'))];
        
        
{ imgSets.Description } % display all labels on one line
[imgSets.Count] ;        

% determine the smallest amount of images in a category
minSetCount = min([imgSets.Count]); 

% Use partition method to trim the set.
imgSets = partition(imgSets, minSetCount, 'randomize');

% Notice that each set now has exactly the same number of images.
[imgSets.Count];
[trainingSets, validationSets] = partition(imgSets, 0.3, 'randomize');



% extract all features using function bagOfFeatures
bag = bagOfFeatures(trainingSets);
img = read(imgSets(1), 1);
featureVector = encode(bag, img);



% Ask user to enter a image category and a test image to get result as the
%category it belongs 
while 1
    %user input for entering image category
    prompt = 'Enter the Category to take test data from or enter "quit" to exit:';
    str_cat = input(prompt,'s');
    if strcmp(str_cat,'quit')
        break
    end
    
    %user input for the sample test image
    prompt2 = 'Enter image file name for testing:';
    str_file = input(prompt2,'s');
    img = imread(fullfile(rootFolder, str_cat, str_file));
    [labelIdx, scores] = predict(categoryClassifier, img);

    % Display the string label
    str_ans = categoryClassifier.Labels(labelIdx)
   
    
end